## ================================================================================================================
#   This file is part of mpv-auto-delete-playlist
#   https://github.com/ExiledEye/mpv-auto-delete-playlist
#
#   mpv-auto-delete-playlist.conf
#   Author: Exiled Eye
#   Version: 1.0
#   Description: Configuration file for the script.
#
#   Copyright (c) 2026 Exiled Eye
#   Licensed under the MPL-2.0 License.
#   Refer to the LICENSE file for details.
## ================================================================================================================

delete_on=end
## end: Delete the playlist file when mpv exits.
## start: Delete the playlist file when mpv starts.
delete_all_in_dir=no
## yes: Delete all playlist files in the directory.
## no: Only delete the currentplaylist file.
permanent=yes
## yes: Delete the playlist file permanently.
## no: Send the playlist file to the recycle bin.
keybinds=yes
## yes: Enable keybinds to quit mpv but not trigger playlist deletion when delete_on=end.
## no: Disable keybinds.
keybind1=ctrl+q
keybind2=shift+q


